services:
  db:
    image: mariadb:11
    container_name: nube-db
    environment:
      MARIADB_DATABASE: empresa
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppass
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - nube-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -uroot -proot || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: ./app-php
    container_name: nube-web
    hostname: nube-web
    environment:
      DB_HOST: nube-db
      DB_PORT: 3306
      DB_NAME: empresa
      DB_USER: appuser
      DB_PASSWORD: apppass
      APP_REQUIRED_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - nube-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:80 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  nube-net:
    driver: bridge

volumes:
  db_data: